name: Godot CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Godot
      uses: lihop/godot-setup@v2.1.3
      with:
        version: 4.3-stable
        export-templates: true

    - name: Build project
      run: godot --export-release "Windows Desktop"
    
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: build/HelloGodot.exe
        
    
            