name: Godot CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Godot
      uses: lihop/godot-setup@v2.1.3
      with:
        version: 4.3-stable
        export-templates: true

    - name: Build project
      run: godot --export-release "Windows Desktop" "build/HelloGodot.exe"

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: HelloGodot
        path: build/HelloGodot.exe

  release:
    needs: build
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: HelloGodot
        path: build

    - name: Get previous tag
      id: prev_tag
      run: echo "::set-output name=tag::$(git describe --tags --abbrev=0 HEAD^1)"
  
    - name: Generate release notes
      id: release_notes
      run: |
        PREV_TAG=${{ steps.prev_tag.outputs.tag }}
        COMMITS=$(git log $PREV_TAG..HEAD --pretty=format:"%h - %s (%an)")
        echo "Release notes between $PREV_TAG and ${{ github.ref }}:" > release_notes.md
        echo "$COMMITS" >> release_notes.md
  
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: build/HelloGodot.exe
        body_path: release_notes.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    
            